TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#ARCH = windows-x64-dynamic
#ARCH = windows-x64
#ARCH = linux-x86
ARCH = linux-x86_64
TARGETS = envPaths dllPath.bat
include $(TOP)/configure/RULES.ioc
